### ISSUE TITLE
add content about target data

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubDocs#183]
We would like some of the content on [this document](https://htmlpreview.github.io/?https://github.com/reichlab/hub-infrastructure-experiments/blob/main/eval-examples/target_data_formats.html) to be reflected in the documentation site, so that hubs can make informed decisions about the recommended best practices for storing target data in hubs.

Per discussion at hub dev meeting on 9/25 it was decided that we would collect any additional feedback over the next week or so and then start translating some of the info in the document above into the documentation as appropriate.

Here is also a relevant [discussion](https://github.com/orgs/hubverse-org/discussions/9#discussioncomment-10492279).

**Comment by zkamvar** [comment]
The terminology for this always escapes me and I want to make sure that we get it right.

From what I understand, we need to overhaul https://hubverse.io/en/latest/user-guide/target-data.html

The [document about target data formats](https://htmlpreview.github.io/?https://github.com/reichlab/hub-infrastructure-experiments/blob/main/eval-examples/target_data_formats.html) describes target data as being one of time series and observations data. 

I think there are some fluid representations that need to be ironed out, especially wrt to "target" and "observation"

 - "target" is a modeling goal (e.g. "weekly influenza hospitalization incidence")
   - "target data" refers to the data _derived from_ ground truth sources
      - [Deprecated synonym: "modeling target"](https://hubverse.io/en/latest/user-guide/target-data.html#calculating-modeling-targets)
      - [Deprecated synonym: "truth data"](https://hubverse.io/en/latest/user-guide/target-data.html#purpose)
   - "model output" refers to the output of the modeling efforts
 - "observation" is a column in target data that has been observed from the truth data
   - in "target time series" this refers to observed incident counts that can be used as input for models
   - in "target observation" this refers to the data that semantically matches with the model output "value" column, arranged by output type.

At the moment, having "target time series" and "target observation" both have a column called "observation" is a bit confusing because (as I understand it), the time series are the directly observed values (which are extracted from the source data) and the "target observation" are _derived_ from those values, but I could be very wrong.


It's largely semantic, but I would like to make sure the terminology is correct.
